### ISSUE TITLE
Move log_signer/Dockerfile and log_server/Dockerfile to root

### ISSUE THREAD

**Issue by lance** [securesign/trillian#9]
When the `./redhat/release/update-to-head.sh` script runs, we should move the two Dockerfiles to the root of the repository and commit that. The RHTAP build system will not work with them in these paths. They need to be at the root or in one of several pre-defined directories. Root seems simplest. Simply `git mv redhat/overlays/log_signer/Dockerfile Dockerfile.log_signer` and the same for the log server in the script just after this `if` block: https://github.com/securesign/trillian/blob/fd0b9bb3dec783f1c2012fb036364d5ca68b48c3/redhat/release/update-to-head.sh#L59-L62

I think this will work. The change needs to be made both on the `master` branch, as well as on the `midstream-v1.5.2` branches - so two separate PRs.

**Comment by tommyd450** [comment]
Makes Perfect Sense I'll make sure to make the necessary adjustments in the Image Factory too.

**Comment by lance** [comment]
Fixed in #11
